<form method="post" action="/filecase/filecase">
    <paper-input name="description" label="Description"></paper-input>
    <paper-input name="case_type" label="Type"></paper-input>
    <div style='display="flex"'>
    <paper-button onclick="document.forms[0].submit();" raised>Submit</paper-button>    
    <paper-button onclick="window.location='filecase/show'" raised>View</paper-button>
    </div>
</form>

