<html>
<head>
    <link rel="import" href="bower_components/common_elements.html">
    <link rel="stylesheet" href="css/main.css">
</head>
<body>

<paper-toolbar id="home-bar">
    <paper-icon-button id="gavel" icon="gavel"></paper-icon-button>
    <span class="title" id="front">Court Hack</span>
    <paper-icon-button id="gavel" icon="perm-identity" onclick="window.location='/login'"></paper-icon-button>
</paper-toolbar>

<div id="img"></div>

<div style="display: flex; justify-content: center;align-items:center; margin-top:40px;margin:10px;">
    <paper-card style="display:flex;width:30%;height:30%;margin:10px;justify-content: center;align-items: center;background:tomato;" elevation="1">Cool Stuff Goes Here</paper-card>
    <paper-card style="display:flex;width:30%;height:30%;margin:10px;justify-content: center;align-items: center;background:tomato;" elevation="1">Awesome Stuff Here</paper-card>
    <paper-card style="display:flex;width:30%;height:30%;margin:10px;justify-content: center;align-items: center;background:tomato;" elevation="1">All I want to do is sleep</paper-card>
</div>

<div style="display:flex;width:100%;height:300px;background:url('../img/front2.jpg') no-repeat center center;background-size:cover; justify-content: center;align-items: center"><h1 style="color:#fff;text-shadow: 1px 2px 1px #000; font-size:59px;">Makeing Problems Easier for Lawmakers & Crooks Alike!</h1></div>

<div style="display: flex; justify-content: center;align-items:center; margin-top:40px;margin:10px;">
    <paper-card style="display:flex;width:30%;height:30%;margin:10px;justify-content: center;align-items: center;flex-grow:2;background:seagreen;" elevation="1">Other Random Greatness</paper-card>
    <paper-card style="display:flex;width:30%;height:30%;margin:10px;justify-content: center;align-items: center;flex-grow:2;background:seagreen;" elevation="1">Raise your hand if you are sleeping</paper-card>

</div>
</body>
</html>

